#-------------------------------
# General Site Settings

#menu:
#- {name: 'Projects', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
#- {name: 'About', url: 'pages/about.html'}
#- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: https://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: #'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'tiagoair'

#-------------------------------
# About Section

about: >
  # Personal portfolio

  
contact: >
  # Contact

 
#-------------------------------
# Work Section

games:
- {name: 'Sleight', folder: 'game-8', file: 'games/game-8.html', link: 'https://store.steampowered.com/app/953110/SLEIGHT__Nerve_Wracking_Espionage_Party_Game'}
- {name: 'Resonance', folder: 'game-7', file: 'games/game-7.html', link: 'https://demeraragames.itch.io/resonance'}
- {name: 'Lag Warfare', folder: 'game-6', file: 'games/game-6.html', link: 'https://gamejolt.com/games/lag-warfare-no-reconnection/171568'}
- {name: 'Fungi', folder: 'game-5', file: 'games/game-5.html', link: 'https://gamejolt.com/games/deep-waters/46386'}
- {name: 'GAZA', folder: 'game-4', file: 'games/game-4.html', link: 'https://gamejolt.com/games/gaza-0-1/31178'}
- {name: 'A Game of Thrones', folder: 'game-3', file: 'games/game-3.html', link: 'https://gamejolt.com/games/a-game-of-thrones/31423'}
- {name: 'RED', folder: 'game-2', file: 'games/game-2.html', link: 'https://gamejolt.com/games/red/423794'}
- {name: 'Heart-Shaped Box', folder: 'game-1', file: 'games/game-1.html', link: 'https://gamejolt.com/games/heart-shaped-box/31476'}


profilepic: 'assets/img/profile.png'

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/tiagoair'}
- {icon: 'envelope', link: 'mailto:tiagoair@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
